package io.antelli.plugin.kurzy.entity

object Currency {
    val EUR = "EUR-euro"
    val GBP = "GBP-britska-libra"
    val AUD = "AUD-australsky-dolar"
    val HKD = "HKD-hongkongsky-dolar"
    val CAD = "CAD-kanadsky-dolar"
    val NZD = "NZD-novozelandsky-dolar"
    val SGD = "SGD-singapursky-dolar"
    val USD = "USD-americky-dolar"
    val DKK = "DKK-danska-koruna"
    val NOK = "NOK-norska-koruna"
    val SEK = "SEK-svedska-koruna"
    val INR = "INR-indicka-rupie"
    val IDR = "IDR-indoneska-rupie"
    val MXN = "MXN-mexicke-peso"
    val PHP = "PHP-filipinske-peso"
    val CNY = "CNY-cinsky-juan"
    val JPY = "JPY-japonsky-jen"
    val HRK = "HRK-chorvatska-kuna"
    val RUB = "RUB-rusky-rubl"
    val ILS = "ILS-izraelsky-sekel"
    val BRL = "BRL-brazilsky-real"
    val BGN = "BGN-bulharsky-lev"
    val ZAR = "ZAR-jihoafricky-rand"
    val KRW = "KRW-jihokorejsky-won"
    val HUF = "HUF-madarsky-forint"
    val MYR = "MYR-malajsijsky-ringgit"
    val PLN = "PLN-polsky-zloty"
    val RON = "RON-rumunsky-novy-lei"
    val CHF = "CHF-svycarsky-frank"
    val THB = "THB-thajsky-baht"
    val TRY = "TRY-turecka-lira"
}
